### ISSUE TITLE
Bed management

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/coldaid-backend#2]
Add the possibility to manage the beds of an accommodation, e.g. add/remove beds, occupy/free beds, change the category of beds etc...

**Comment by andreasmaucher** [comment]
![IMG_4121](https://user-images.githubusercontent.com/57959338/71914480-f89c0600-3179-11ea-801a-3416624176c9.jpg)

**Comment by andreasmaucher** [comment]
There are two new different pages in the Backend necessary (similar to the page for POIs):
1. page for the one-time entry of the basic data (how many beds in total and for the different categories are available), there is no field for pets or drug influence as these characteristics should be included for each shelter and not per bed
2. page for the management of the beds by the service providers (Unterkünfte), this page pulls the data from 1. and via a separate field with +/- the shelter managers can adjust the number of beds that are currently available; on the bottom the number of free beds is automatically calculated. (is it possible that the data in this sheet are deleted automatically at the end of every night,maybe link this to the opening hour or should this be done manually?)
